[package]
name = "rust-random-chat"
version = "0.1.0"
authors = ["wes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10.1"
lazy_static = "1.4.0"
